# Generated by Django 3.2.19 on 2024-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_posts_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
