# Generated by Django 4.2.15 on 2024-08-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20240826_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posted_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='posted_by',
            new_name='tags',
        ),
    ]
