# Generated by Django 4.2.15 on 2024-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_posted_at_posts_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='app1.tagline'),
        ),
    ]
