# Generated by Django 4.2.15 on 2024-08-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_tagline_posts_slug_remove_posts_tags_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
