# Generated by Django 3.2.19 on 2024-08-29 05:57

import dish_names.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=dish_names.models.image_name_with_file_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.category')),
            ],
        ),
    ]
