# Generated by Django 4.2.15 on 2024-08-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_post_delete_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_description', models.CharField(max_length=500)),
                ('image', models.URLField(max_length=500)),
                ('posted_at', models.DateTimeField()),
                ('posted_by', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
